### ISSUE TITLE
Missing Helasat 39E

### ISSUE THREAD

**Issue by Saentist** [oliv3r/dtv-scan-tables#26]
# Hellas sat @ 39E
# freq pol sr fec
S 10955000 V 4444000 AUTO
S 10959000 V 3300000 AUTO  
S 10964000 V 3300000 AUTO  
S 10973000 V 3125000 AUTO  
S 10977000 V 3125000 AUTO  
S 10984000 V 5000000 AUTO  
S 11012000 V 30000000 AUTO 
S 11078000 V 3333000 AUTO  
S 11083000 V 6333000 AUTO
S 11097000 H 6111000 AUTO
S 11104000 V 14400000 AUTO
S 11119000 V 1500000 AUTO
S 11123000 V 3000000 AUTO
S 11126000 V 1450000 AUTO
S 11131000 V 3300000 AUTO
S 11135000 V 30000000 AUTO
S 11141000 V 3300000 AUTO
S 11150000 V 3300000 AUTO
S 11455000 H 3224000 AUTO
S 11464000 H 3224000 AUTO
S 11469000 H 3224000 AUTO
S 11473000 H 4444000 AUTO
S 11479000 H 3190000 AUTO
S 11482000 H 2905000 AUTO
S 11486000 H 2509000 AUTO
S 11551000 H 2700000 AUTO
S 11561000 H 2905000 AUTO
S 11565000 H 2250000 AUTO
S 11608000 H 2100000 AUTO
S 11611000 H 2100000 AUTO
S 11619000 H 3333000 AUTO
S 11624000 V 3255000 AUTO
S 11625000 H 3333000 AUTO
S 11649000 H 4433000 AUTO
S 11681000 H 7600000 AUTO
S 11692000 H 2300000 AUTO
S 12524000 V 30000000 AUTO
S 12524000 H 30000000 AUTO
S 12565000 V 30000000 AUTO
S 12565000 H 30000000 AUTO
S 12596000 V 14050000 AUTO
S 12606000 H 30000000 AUTO
S 12615000 V 15000000 AUTO
S 12647000 H 30000000 AUTO
S 12647000 V 30000000 AUTO
S 12688000 V 30000000 AUTO
S 12688000 H 30000000 AUTO
S 12729000 V 30000000 AUTO

**Comment by oliv3r** [comment]
Sorry for the late reply, but you probably better submit a pull request rather then this, as I don't know what you want me to do with this?
