### ISSUE TITLE
New DVB-T2 Frequencies Germany

### ISSUE THREAD

**Issue by Mettbrot** [oliv3r/dtv-scan-tables#39]
Here are the new Frequencies for Germany: http://dvb-t2hd.de/files/Senderstandorte_und_Kanaele_(November_2017).pdf

**Comment by oliv3r** [comment]
Hi Mettbrot,

Sorry for not seeing this issue, I didn't realize people where filing issues.
I'm happy to merge your tested changes, but going from just a pdf is a little too risky to just create/modify these files. I'm happy to merge your tested changes however!
